import { IIrregularType } from '../types/reduxTypes';

export const irregularList:IIrregularType[] = [
     { infinitiv: 'potrebovati', mutated: 'potrebuje', means : 'to need' },  
     { infinitiv: 'potovati', mutated: 'potuje', means : 'to travel' },  
     { infinitiv: 'svetovati', mutated: 'svetuje', means : 'to advise' },  
     { infinitiv: 'Imeti', mutated: 'ima', means : 'to have' }, 
     { infinitiv: 'končevati', mutated: 'končuje', means : 'to finish' },  
     { infinitiv: 'vključevati', mutated: 'vključuje', means : 'to include' },  
     { infinitiv: 'reči', mutated: 'reče', means : 'to say' },  
     { infinitiv: 'teči', mutated: 'teče', means : 'to run' },  
     { infinitiv: 'vleči', mutated: 'vleče', means : 'to pull' },  
     { infinitiv: 'obleči se', mutated: 'obleče se', means : 'to get dressed' },  
     { infinitiv: 'peči', mutated: 'peče', means : 'to bake' },  
     { infinitiv: 'vreči', mutated: 'vrže', means : 'to need' },  
     { infinitiv: 'preseči', mutated: 'preseže', means : 'to exceed' },  
     { infinitiv: 'leči', mutated: 'leže', means : 'to lie down' },  
     { infinitiv: 'pisati', mutated: 'piše', means : ' to write' },  
     { infinitiv: 'risati', mutated: 'riše', means : 'to to draw' },  
     { infinitiv: 'iti', mutated: 'gre', means : 'to go' },  
     { infinitiv: 'jesti', mutated: 'je', means : 'to eat' },  
     { infinitiv: 'piti', mutated: 'pije', means : 'to drink' },  
     { infinitiv: 'brati', mutated: 'bere', means : 'to read' },  
     { infinitiv: 'vedeti', mutated: 've', means : 'to know' },  
     { infinitiv: 'najti', mutated: 'najde', means : 'to find' },  
     { infinitiv: 'iskati', mutated: 'išče', means : 'to look for' },  
     { infinitiv: 'živeti', mutated: 'živi', means : 'to live' },  
     { infinitiv: 'moči', mutated: 'more', means : 'to be able to' },  
     { infinitiv: 'hoteti', mutated: 'hoče', means : 'to want' },  
     { infinitiv: 'pasti', mutated: 'pade', means : 'to fall' },  
     { infinitiv: 'spati', mutated: 'spi', means : 'to sleep' },  
]